### PR TITLE
Install archived yarn versions

### LINKED ISSUE #271: Unable to install version `1.1.0-exp.2`
**Describe the bug**
Installing version `1.1.0-exp.2` fails. It is a valid version but currently yvm doesn't allow to install it. 

**To Reproduce**
1. `yvm i 1.1.0-exp.2`
2. See error

**Expected behavior**
It should install version `1.1.0-exp.2`

**Screenshots**
image

### PR DESCRIPTION
**Pull request by iamogbz**
## Description

This should resolve #271.

### DevQA Prep

- Please `make install-watch`

### DevQA Steps

- Should complete successfully and use latest yarn
  - `yvm i -l`
  - `yvm use <LATEST_YARN_VERSION>`
  - `yarn --version`
- Should complete successfully and use installed yarn
  - `yvm i 1.12.0`
  - `yvm use 1.12.0`
  - `yarn --version`
- Should not complete but print appropriate instructions
  - `yvm install 1.3.0`
- Should not complete but print appropriate instructions
  - `yvm i 1.1.0-exp.2`
- Should list all available yarn versions indicating installed versions
  - `yvm ls-remote`

### Comments:

- This is caused by a defective yarn release. https://github.com/yarnpkg/yarn/issues/4828
  - Though yarn can be build from source, `yvm` will not support these broken releases

### CODE REVIEW

File: src/commands/install.js [hunk 1]
```diff
@@ -115,33 +128,40 @@ const installVersion = async (version, rootPath = yvmPath) => {
...
         log(
             'You have provided an invalid version number. use "yvm ls-remote" to see valid versions.',
         )
         throw new Error('Invalid version number provided')
     }
 
     log(`Installing yarn v${version} in ${rootPath}`)
-    await downloadVersion(version, rootPath)
-
+    const hasSig = await downloadVersion(version, rootPath, releases[version])
```
Comment (jakebolam) [inline src/commands/install.js]: [nb] full names `hasSignature`

File: src/commands/install.js [hunk 2]
```diff
@@ -30,10 +32,16 @@ const isVersionInstalled = (version, rootPath) => {
     return fs.existsSync(versionPath)
 }
 
-const downloadVersion = (version, rootPath) => {
+const downloadVersion = async (version, rootPath, releaseInfo) => {
     const url = getUrl(version)
     const filePath = getDownloadPath(version, rootPath)
-    return downloadFile(url, filePath)
+    try {
+        await downloadFile(url, filePath)
```
Comment (jakebolam) [inline src/commands/install.js]: [nb] not sure if we should use releaseInfo for this too?

File: src/commands/install.js [hunk 3]
```diff
@@ -78,27 +86,32 @@ const verifySignature = async (version, rootPath) => {
...
                     reject(err)
                 } else {
                     log(`Finished extracting yarn version ${version}`)
-                    fs.renameSync(
-                        `${destPath}/yarn-v${version}`,
-                        `${destPath}/v${version}`,
-                    )
-                    fs.unlinkSync(srcPath)
-                    resolve()
+                    const [pkgDir] = fs.readdirSync(tmpPath)
```
Comment (jakebolam) [inline src/commands/install.js]: Why the change in behaviour here?

File: src/util/download.js [hunk 4]
```diff
@@ -1,17 +1,19 @@
...
-        })
+const downloadFile = (url, filePath) =>
+    new Promise((resolve, reject) => {
+        const handleError = err => reject(err)
+        request
+            .get(url, { headers: { 'user-agent': 'yvm' } })
+            .on('error', handleError)
+            .on('response', r => {
+                const msg = `HTTP ${r.statusCode} - ${r.statusMessage} (${url})`
+                if (r.statusCode === 404) handleError(msg)
```
Comment (jakebolam) [inline src/util/download.js]: if not 200 ?

File: src/commands/install.js (hunk 2 above)
Comment (jakebolam) [reply src/commands/install.js]: Does release use the mirror download?

File: src/commands/install.js [hunk 5]
```diff
@@ -115,33 +128,40 @@ const installVersion = async (version, rootPath = yvmPath) => {
...
 
-    log('GPG signature validated')
-    return extractYarn(version, rootPath)
+    let continueInstall
+    if (hasSig) {
+        await verifySignature(version, rootPath)
+        log('GPG signature validated')
+        continueInstall = true
+    } else {
+        const keyword = 'yes'
```
Comment (jakebolam) [inline src/commands/install.js]: Instead of using input. Can we say run `yvm install --ignore-signature` ?
(I understand there are cases we try to auto install, but for these cases I think its fine to fail)

File: src/util/utils.js [hunk 6]
```diff
@@ -32,18 +32,24 @@ const getVersionsFromTags = () => {
                 reject(error)
             } else {
                 const tags = JSON.parse(body)
-                const tagNames = tags.map(tag => tag.name)
-                const versions = tagNames
-                    .map(stripVersionPrefix)
-                    .filter(version => version[0] > 0)
-                resolve(versions)
+                const releases = tags.reduce((accumulator, tag) => {
```
Comment (jakebolam) [inline src/util/utils.js]: Whats the motivation behind this change?

File: src/commands/install.js (hunk 2 above)
Comment (iamogbz) [reply src/commands/install.js]: The `tarball_url` in the cf release info is the src which is much larger. I was thinking use this only as a fallback url.

File: src/commands/install.js (hunk 3 above)
Comment (iamogbz) [reply src/commands/install.js]: The extracted file from the fallback `tarball_url` doesn't follow the same naming pattern. However it's still one content folder when extracted.

File: src/commands/install.js (hunk 5 above)
Comment (iamogbz) [reply src/commands/install.js]: That probably better fits with the existing pattern 👍

File: src/util/download.js (hunk 4 above)
Comment (iamogbz) [reply src/util/download.js]: It could be a redirect as well. Will update to use the range `2xx` to `3xx`.

File: src/util/utils.js (hunk 6 above)
Comment (iamogbz) [reply src/util/utils.js]: Needed the full release info by version to get the fallback `tarball_url`. Preserved the `getVersionsFromTags` fn contract below.

File: src/commands/install.js [hunk 7]
```diff
@@ -78,34 +86,48 @@ const verifySignature = async (version, rootPath) => {
...
                 }
             },
         )
     })
 }
 
-const installVersion = async (version, rootPath = yvmPath) => {
+const buildYarn = srcPath => {
+    const options = { cwd: srcPath, stdio: 'inherit' }
+    execSync('yarn install && yarn run build', options)
```
Comment (jakebolam) [inline src/commands/install.js]: Installing these versions of yarn need building?

Comment (jakebolam) [reply src/commands/install.js]: Seems super weird that we need this.

I think we either target the yarn version installed for yvm directly. (We installed yarn we know where it is) then perhaps exit if none installed.

Or maybe we just don't support these versions?

Comment (iamogbz) [reply src/commands/install.js]: Switched to using `npm` as it comes with `node` which is a requirement

File: README.md [hunk 8]
```diff
@@ -206,7 +206,7 @@ Thanks goes to these wonderful people ([emoji key](https://github.com/kentcdodds
...nfra-jakebolam "Infrastructure (Hosting, Build-Tools, etc)") | [<img src="https://avatars1.githubusercontent.com/u/39271619?v=4" width="100px;"/><br /><sub><b>Brandon Baksh</b></sub>](https://www.linkedin.com/in/brandonbaksh/)<br />[💻](https://github.com/tophat/yvm/commits?author=brandonbaksh "Code") | [<img src="https://avatars3.githubusercontent.com/u/2070398?v=4" width="100px;"/><br /><sub><b>Milan Milojic</b></sub>](https://github.com/nepodmitljivi)<br />[💻](https://github.com/tophat/yvm/commits?author=nepodmitljivi "Code") | [<img src="https://avatars2.githubusercontent.com/u/38886386?v=4" width="100px;"/><br /><sub><b>Umar Ahmed</b></sub>](https://github.com/umar-tophat)<br />[💻](https://github.com/tophat/yvm/commits?author=umar-tophat "Code") | [<img src="https://avatars0.githubusercontent.com/u/3258756?v=4" width="100px;"/><br /><sub><b>Nicholas Dujay</b></sub>](https://github.com/dat2)<br />[💻](https://github.com/tophat/yvm/commits?author=dat2 "Code") | [<img src="https://avatars0.githubusercontent.com/u/3996927?v=4" width="100px;"/><br /><sub><b>Aser Eldamaty</b></sub>](https://github.com/aeldamaty)<br />[💻](https://github.com/tophat/yvm/commits?author=aeldamaty "Code") |
```
Comment (jakebolam) [inline README.md]: there is an all contributors badge at the top which needs incrementing (it should have happened automatically)

File: src/yvm.js [hunk 9]
```diff
@@ -35,20 +35,15 @@ argParser
...
-        if (maybeVersion) {
-            installVersion(maybeVersion).catch(error => {
-                log(error)
-                process.exit(1)
-            })
-            return
-        }
-        const [defaultVersion] = getSplitVersionAndArgs()
-        installVersion(defaultVersion).catch(error => {
+        const { fn: installFn, options } = command.latest
```
Comment (jakebolam) [inline src/yvm.js]: [nb] imo this is far harder to read and understand than the original code

File: README.md (hunk 8 above)
Comment (iamogbz) [reply README.md]: I don't think it did. I just ran the command, will run it again, assuming it's idempotent

File: src/yvm.js (hunk 9 above)
Comment (iamogbz) [reply src/yvm.js]: Refactored

File: src/util/log.js [hunk 10]
```diff
@@ -15,4 +15,10 @@ log.info = function errorLog(...args) {
     }
 }
 
+log.colors = {
+    RED: '\x1b[31m%s\x1b[0m',
```
Comment (jakebolam) [inline src/util/log.js]: Thoughts on using chalk? https://github.com/tophat/yvm/pull/205/files

**Comment by jakebolam** [comment]
LGTM?
