### PR TITLE
fix: commands break inelegantly without internet connection

### LINKED ISSUE #342: Commands break inelegantly without internet connection
**Describe the bug**

When there's no network connection some commands break with an ugly exception message.

**To Reproduce**
1. Install latest version
2. Run any of the commands without a network connection
  - `yvm install 1.15.2` <- version not already installed
  - `yvm use 1.13.0` <- ^
  - `yvm ls`
  - `yvm ls-remote`
  - `yvm alias`
3. See error

**Expected behavior**
yvm gracefully completes tasks or fails **AND** informs user that there's no network connection when it's required.

**Desktop (please complete the following information):**
 - OS: macOS
 - YVM Version: v3.0.0
 - Shell: bash/fish
 - Node version: v8.11.3

**Additional context**

### PR DESCRIPTION
**Pull request by iamogbz**
## Description

- Messaging around no network connection

### Checklist
- [x] This PR has updated documentation
- [x] This PR has sufficient testing

### DevQA Prep

- Please `make install`

### DevQA Steps

- Switch off network connection
- `yvm install 1.15.2` <- version not already installed
- `yvm use 1.13.0` <- ^
- `yvm ls`
- `yvm ls-remote`
- `yvm alias`

### Comments

Fixes #342

### CODE REVIEW

File: src/util/utils.js [hunk 1]
```diff
@@ -57,5 +58,12 @@ export const getReleasesFromTags = memoize(async () => {
...
 export const getVersionsFromTags = memoize(async () => {
-    return Object.keys(await getReleasesFromTags())
+    try {
+        return Object.keys(await getReleasesFromTags())
+    } catch (e) {
+        log.error(
+            'Unable to retrieve remote versions. Please check your network connection',
+        )
+        return []
+    }
```
Comment (iamogbz) [inline src/util/utils.js]: This is the main fix, most else is tests.
